version: "3.9"

services:
  # ################################################################################
  # Database
  # ################################################################################
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -t 5 -U ${POSTGRES_USER} || false"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # ################################################################################
  # Caching
  # ################################################################################

  # ################################################################################
  # Django Backend / API
  # ################################################################################
  web:
    build: .
    volumes:
      - ./:/workspace
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    ports:
      - "8001:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
  # ################################################################################
  # Celery scheduler/worker
  # ################################################################################


volumes:
  postgres_data:
