# Generated by Django 4.2.7 on 2024-06-02 23:34

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start', models.TimeField(blank=True, default=None, help_text='Врямя начала работы кабинета', null=True)),
                ('end', models.TimeField(blank=True, default=None, help_text='Врямя окончания работы кабинета', null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Cabinet',
                'verbose_name_plural': 'Cabinet',
            },
        ),
    ]
