# Generated by Django 4.2.7 on 2024-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0002_cabinet_delete_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='end',
            field=models.TimeField(blank=True, default=None, help_text='Врямя окончания работы кабинета', null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='start',
            field=models.TimeField(blank=True, default=None, help_text='Врямя начала работы кабинета', null=True),
        ),
    ]
