# Generated by Django 4.2.7 on 2024-04-30 01:05

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0002_cabinet_delete_quiz'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('cabinet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='cabinets.cabinet', verbose_name='cabinet')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='doctors.doctor', verbose_name='doctor')),
            ],
            options={
                'verbose_name': 'Interval',
                'verbose_name_plural': 'Intervals',
            },
        ),
    ]
