# Generated by Django 5.1.4 on 2025-01-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
