# Generated by Django 4.2.7 on 2025-05-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('intervals', '0002_interval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='client',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='clients.client', verbose_name='client'),
        ),
    ]
