# Generated by Django 4.2.7 on 2025-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0003_interval_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='notification',
            field=models.BooleanField(default=True, verbose_name='notification'),
        ),
    ]
