# Generated by Django 5.0.6 on 2024-06-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='User with premium status', verbose_name='Is premium'),
        ),
    ]
